### ISSUE TITLE
Add logging for additional RPC types

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-showcase#10]
Unary requests are logged to stdout but other types are not (streaming, etc.): 

https://github.com/googleapis/gapic-showcase/blob/c7d0008906adbbad38af53ce8a62d71a2e85b6f5/cmd/server/main.go#L91

Similar logging for additional RPC types would be helpful.

**Comment by landrito** [comment]
Resolved in #11

**Comment by jbolinger** [comment]
Thanks! I'll try to update soon.
