### ISSUE TITLE
Unknown enum value is still a number even without alt parameter

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-showcase#1202]
ShowCase version: 0.25.0.

In order to simulate an enum value which is unknown to the client but known to the server, the ShowCase server should return a *string* representation instead of a numeric value for compliance/enum

Sample request:

```sh
curl -H "X-Goog-Api-Client: gapic/ rest/" http://localhost:7469/v1beta1/compliance/enum?unknownEnum=true
```

Expected result:

```sh
{
  "request":  {
    "unknownEnum":  true
  },
  "continent":  "SomeUnknownStringValue"
}
```

Actual result:

```sh
{
  "request":  {
    "unknownEnum":  true
  },
  "continent":  -32720
}
```

The current behavior means we're not actually testing whether the client is sending the appropriate alt parameter - just whether the protobuf library can parse numeric enum values.

**Comment by vchudnov-g** [comment]
The intent of the `GetEnum` and `VerifyEnum` RPCs has been merely to pin down that with the parameters set correctly, we can indeed round-trip an unknown value from the server. This _assumes_ the correct value of `$alt` and so returns a number. This was not meant  to verify that we're sending the numeric alt parameter. 

The same [PR](https://github.com/googleapis/gapic-showcase/pull/1159) that implemented that also implemented allowing but not requiring that Showcase accept and respond to the `$alt` parameter. A future PR will have Showcase requiring the numeric enum parameter (tracked internally as b/242338676)

**Comment by jskeet** [comment]
Okay - so it's really just "does the client library parse numbers" at the moment? I guess if we later require the parameter, it'll achieve the right result.

**Comment by vchudnov-g** [comment]
Yes, I think we can close this, unless you have a use case for having Showcase return a string unknown enum. Which might be useful for some of the other proto work you and I are doing.

**Comment by jskeet** [comment]
No immediate need :)
