### ISSUE TITLE
Flaky Streaming Test

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-showcase#123]
There is a test that is flaky in getting a line covered in codecov. It would be nice to fix it:
https://codecov.io/gh/googleapis/gapic-showcase/src/7e7668c1fe6e9ae0f9552198fba94da02145e986/server/messaging_service.go#L487

**Comment by vchudnov-g** [comment]
@noahdietz Any updates on this? We're out of SLO.

**Comment by noahdietz** [comment]
I don't see how this is a bug, rather than just a chore to fix coverage systems, and as the original comment states, a "nice to fix". Changing the label.

**Comment by noahdietz** [comment]
Looks like the flaky line moved to a [different spot] as of late. This doesn't seem like anything we can fix, but rather an issue with CodeCov. I'm going to close this.

[different spot]: https://codecov.io/gh/googleapis/gapic-showcase/src/bd1cc3075ce8255a2b577be6120f8cb1deb96048/server/services/messaging_service.go#L601
