### ISSUE TITLE
Add release asset for running on apple silicon

### ISSUE THREAD

**Issue by leahecole** [googleapis/gapic-showcase#1260]
Hi - I am a googler working on node gax and was trying to run the [showcase server from gax-nodejs](https://github.com/googleapis/gax-nodejs/blob/main/test/showcase-server/src/index.ts). That process downloads a release image, and I figured out that there isn't currently an asset distributed that's compatible with Apple silicon (only darwin amd, linux, and windows.)

 I saw that the application is written in go, and figured out I'm able to run this locally as a workaround because go is great at compiling to different runtimes, but given that Apple silicon is becoming more ubiquitous, it feels like it's time to make sure we have the asset available for use cases like gax showcase server tests! 🍎 😄

**Comment by noahdietz** [comment]
For sure this makes a lot of sense. I _think_ it should be as easy as adding the desired `os`/`arch` combination in our binary release [matrix](https://github.com/googleapis/gapic-showcase/blob/b94ecfc51059b49770e5bdb6f0d7ea07903158e8/.github/workflows/assets.yaml#L38-L51).

I _think_ it would be something like:
```yaml
- os: darwin
  arch: arm64
```

...and then it should "just work".

Does that sound right to you?

**Comment by leahecole** [comment]
Yup, I also think it should be something along those lines given how easy go makes it to compile to different runtimes.

**Comment by noahdietz** [comment]
https://github.com/googleapis/gapic-showcase/releases/tag/v0.26.0 contains assets compiled for `darwin/arm64` - hope it works!
