### ISSUE TITLE
HttpJson Mixins RPCs (Locations & IAM) Not Supported

### ISSUE THREAD

**Issue by lqiu96** [googleapis/gapic-showcase#1299]
In the genrest.go code to generate the handlers: https://github.com/googleapis/gapic-showcase/blob/aba8edb14aa88056a6a60b9a8d59405819e0d634/server/genrest/genrest.go#L33

there is no code to generate the mixins RPCs handlers. When calling this via Java, we are seeing a 400 Bad Request:

Client Recieves:
```
Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
GET http://localhost:7469/v1beta1/projects/showcase/locations/us-central1
{"error":{"code":400,"message":"unrecognized request: GET \"/v1beta1/projects/showcase/locations/us-central1\"","details":null,"Body":"","Header":null,"Errors":null}}
	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
	at com.google.api.gax.httpjson.HttpRequestRunnable.run(HttpRequestRunnable.java:118)
```

Server sends:
```
unrecognized request: GET "/v1beta1/projects/showcase/locations/us-central1"
```

Possible Fix:
- Manually add the Mixin RPCs for *one* client (i.e. Echo) here: https://github.com/googleapis/gapic-showcase/blob/aba8edb14aa88056a6a60b9a8d59405819e0d634/util/genrest/goviewcreator.go#L292

**Comment by noahdietz** [comment]
Looks like there was a TODO to add these and I didn't DO! I've got something started for this.

**Comment by lqiu96** [comment]
Wow, thanks for being so quick with this @noahdietz! FYI, this change isn't blocking anything on Java-side yet so we're not in a rush with this. Thanks again for immediately jumping on this :)

**Comment by noahdietz** [comment]
No problem, it was easy and definitely necessary.
