### ISSUE TITLE
Add a configurable wait time between messages sent for server streaming RPCs  

### ISSUE THREAD

**Issue by blakeli0** [googleapis/gapic-showcase#1306]
We want to add a showcase test for server stream wait timeout that is introduced in this [PR](https://github.com/googleapis/gapic-generator-java/pull/1473), but found that this is not supported at this moment.

Potential solution:
- Add a field `serverStreamWaitTime`  to [ExpandRequest](https://github.com/googleapis/gapic-showcase/blob/e57a36aa5b8ef186de3bfe111dbb7dc8e03deb7f/schema/google/showcase/v1beta1/echo.proto#L210-L216)
- Add a sleep time [here](https://github.com/googleapis/gapic-showcase/blob/e57a36aa5b8ef186de3bfe111dbb7dc8e03deb7f/server/services/echo_service.go#L56) based on the value set above.

**Comment by noahdietz** [comment]
Cool, yeah makes sense. Thanks for the PR
