### ISSUE TITLE
Add a bazel integration test 

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-showcase#1476]
An integration test should be added to ensure a successful build for the following bazel target

https://github.com/googleapis/gapic-showcase/blob/102c10a8f8f698c6edf40dbe3d7f03e3eef3ee68/schema/google/showcase/v1beta1/BUILD.bazel#L29-L46

See https://github.com/googleapis/gapic-showcase/issues/1475 where the bazel target could not be built at HEAD

**Comment by noahdietz** [comment]
lmk if you want me to take this, otherwise, assign it to yourself if you are adding it already
