### ISSUE TITLE
Add support for printing REST request headers in verbose mode using gapic-showcase run -v

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-showcase#1494]
[Release v0.9.0](https://github.com/googleapis/gapic-showcase/blob/main/CHANGELOG.md#v090--2020-04-22) includes support for printing gRPC request headers in verbose mode using `gapic-showcase run -v` but equivalent support is missing for REST transport.

**Comment by noahdietz** [comment]
We spoke about this briefly here, worth taking a look: https://github.com/googleapis/gapic-showcase/pull/1440#issuecomment-1928187893
