### ISSUE TITLE
Dart support

### ISSUE THREAD

**Issue by joeblew99** [googleapis/gapic-showcase#210]
The old gapic-generator-go demo called "Kiosk" supported dart.
https://github.com/googleapis/kiosk/tree/master/dart

Also on a side note, the libs are here, but nothing happening.
https://github.com/googleapis/gapic-generator-dart
https://github.com/googleapis/gax-dart.

Any ideas best way to approach this ?

**Comment by noahdietz** [comment]
You can still call both of these APIs from a Dart application and you can still generate the Dart gRPC clients, they don’t need to be checked in. We experimented with implementing showcase in another language and decided it was unnecessary given the availability of the server binaries and the ease of generating clients.
