### ISSUE TITLE
Echo service does not annotate OAuth scopes

### ISSUE THREAD

**Issue by pongad** [googleapis/gapic-showcase#24]
I believe this annotation is required by the spec, and we should annotate it here. Since the spec states

> for all practical purposes, these annotations [...] must be defined in order to output a reasonable artifact

I think the generators are within their rights to error out if scopes are not defined.

**Comment by jbolinger** [comment]
I would suggest keeping this as optional, or perhaps issue a warning vs an error. It's nice to get up and running without having to setup security on the backend.

It might even be useful to have a showcase service that is secured and another that is not as part of the complete test suite.

**Comment by pongad** [comment]
My argument is not as much that the server isn't secured, it's more that successfully generating clients for protos without this annotation seems to disagree with the spec. Perhaps I'm treating the spec too seriously...

**Comment by lukesneeringer** [comment]
The spec should be the arbiter, but the spec may also be wrong. :-) It is reasonable to argue that the spec is wrong and we should change it.

That said, in the short term, forgetting this and then having your client not work seems like a much more common mistake. _At minimum_ we need a warning.

**Comment by lukesneeringer** [comment]
Closing this as stale.
