### ISSUE TITLE
inconsistent type of resource `Blurb` in `messaging.proto`

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/gapic-showcase#295]
In`messaging.proto` resource Blurb has type : `google.showcase.com/Blurb` but referenced by type `showcase.googleapis.com/Blurb`. Based on annotation rules, It should be `showcase.googleapis.com/Blurb`. 

ref: https://github.com/googleapis/gapic-generator-typescript/pull/280

**Comment by xiaozhenliu-gg5** [comment]
Just checked the proto file, seems the `messaging.proto` here has the correct resource type for `Blurb`. But I copied the `messaging.proto` from `gapic-generator/showcase-protos`which is generated from the showcase test in `circleCI`,  it downloads the `gapic-showcase v0.2.0` from release page. I will regenerate the client to see if I can reproduce the problem. Thanks!

**Comment by xiaozhenliu-gg5** [comment]
Created bug here: https://github.com/googleapis/gapic-generator/issues/3095 
Seems the `gapic-showcase v0.2.0` has the wrong resource type, but newer version fixed it. Not sure we want to fix proto file for v0.2.0, but we need to update the version for `gapic-generator` test.

**Comment by noahdietz** [comment]
Thanks for the research and opening the other bug. I will close this one. If there is anything left to do in this project, feel free to reopen it.
