### ISSUE TITLE
FYI: Cloud Run provides SSL termination and limited gRPC support

### ISSUE THREAD

**Issue by timburks** [googleapis/gapic-showcase#446]
I noticed this in the gapic-showcase README: 

> Note: You can make requests to this server from your own client but an insecure channel must be used since the server does not implement auth. Client library generators with Showcase-based integration tests need to provide the insecure channel to the client library in the tests.

I've been running a gRPC service on Cloud Run - and there I've found that Cloud Run provides automatic SSL termination of hosted services, including gRPC ([docs](https://crun/docs/triggering/https-request)). Streaming methods are still unsupported, so deploying Showcase to Cloud Run right now would have limited usefulness: we get SSL but lose streaming (though it might be worth trying just to see how it breaks).

**Comment by noahdietz** [comment]
Thanks for the FYI! We won't be hosting showcase anytime soon, so I'm going to close this.
