### ISSUE TITLE
0.0.8 descriptor is mysteriously missing LRO annotations.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-showcase#52]
The published descriptor on the releases page seems to have dropped the LRO annotations somehow.

I created the same descriptor locally and it seems to have them (the generator works, _and_ I can eyeball the compiled descriptor and find the annotation values).

[This gist](https://gist.github.com/lukesneeringer/89c2c837704cb90b345cdb8015d55181) has both the locally-generated descriptor and the one on GitHub.

**Comment by landrito** [comment]
Fixed in 0.0.9
