### ISSUE TITLE
Easier LRO end time specification.

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-showcase#62]
https://github.com/googleapis/gapic-showcase/blob/add056576c83b0f7e9819e4bb8227cdbb7935dbe/schema/echo.proto#L153

It would be really nice if this followed AIP-214:

```proto
oneof end {
  google.protobuf.Timestamp end_time = 1;
  google.protobuf.Duration ttl = 2;
}
```

**Comment by landrito** [comment]
Ack! Thanks for letting me know. v0.0.10 will include this change
