### ISSUE TITLE
Wait method uses LRO exclusively

### ISSUE THREAD

**Issue by jbolinger** [googleapis/gapic-showcase#66]
The `wait` method in the `echo.proto` was changed to an LRO sometime after the 0.5 release.

The LRO method is useful, but removing the normal method prevents testing retry functionality. For context, waiting for an LRO vs. retrying a failed operation are distinct and non-related events in the Kotlin generator. This change allows me to test the former (+1) but no longer covers the later case. 

Could you consider adding the normal method in addition to the LRO one (i.e. a method that fails until the requested amount of time has elapsed?)

**Comment by jbolinger** [comment]
friendly ping...  any thoughts on this?

**Comment by landrito** [comment]
I think we switched away from the wait method since we didn't know if it would add too much value. I am +1 on adding this method.

**Comment by jbolinger** [comment]
@noahdietz I think this test is useful for retry. Since you've sorted much of that out now should we consider adding this back to showcase?

**Comment by noahdietz** [comment]
So to make sure I understand things, you want to add a `WaitRegular` method or something that doesn't return an LRO, but rather a `WaitResponse` so that we can test RPCs that take more time and the retry functionality for such RPCs?

> Since you've sorted much of that out now 

What have I sorted out? :sweat_smile:

**Comment by jbolinger** [comment]
Yes, Ernest had an API for that in an early version of showcase and then dropped it in favor of this. I just want to bring it back because I think they are both useful to have.

**Comment by noahdietz** [comment]
Ok! Fine by me. I think if we can find whatever we had before and just reintroduce it, that would be best. 

Are you taking this or do we need to find someone to take it on?

**Comment by jbolinger** [comment]
I'll try and see if I can dig up the old implementation.

I know the goal is to keep the `echo` service pretty minimal so I just wanted to run it by someone first.
