### ISSUE TITLE
Does Showcase support grpc-fallback?

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-showcase#83]
I thought perhaps it might, since maybe it would be built into gRPC. It does not seem to, though.
Not sure what would need to happen for us to be able to reliably test gRPC-fallback, but it is probably worth at least finding out what the effort would be.

**Comment by landrito** [comment]
As it is right now, it does not support gRPC-fallback. I _think_ someone has already written a proxy to do that but I'd have to look into it.

**Comment by landrito** [comment]
Ah https://github.com/grpc-ecosystem/grpc-gateway is a thing. I think prioritizing that proxy implementation after the implementation of the server-side validation would be a good next step.

**Comment by landrito** [comment]
Oh actually this looks much easier than I thought. Might be good to just do it since it seems like O(hours) of work.

**Comment by jbolinger** [comment]
If you add it please leave the un-proxied path exposed.

**Comment by landrito** [comment]
Agh it appears I was mistaken. grpc-gateway is a reverse proxy that accepts JSON rather than proto binarys over http. This will be harder.

**Comment by lukesneeringer** [comment]
In a perfect world, perhaps gRPC could add this to gRPC itself? :-O

**Comment by timburks** [comment]
@sergiocampama added it to grpc-swift: https://github.com/grpc/grpc-swift/pull/350 

In this case it was easy to add to the same http server that was serving gRPC. The consensus with Wenbo is that gRPC language implementations would only do this when it's easy and in general it would get handled by proxies. But I'm not aware of an existing proxy that we can use yet for this.

**Comment by noahdietz** [comment]
I added a Unary RPC proxy for grpc-fallback in #144. The grpc-fallback proxy is accessible on `:1337`.
