### ISSUE TITLE
Guard against out of bounds page tokens.

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-showcase#90]
There is a chance that a user can send a page token that can be parsed but is out of bounds which would cause a seg fault. This needs to be fixed across all tokenized requests.

**Comment by vchudnov-g** [comment]
@noahdietz Any updates on this? We're out of SLO.

**Comment by noahdietz** [comment]
No work has started and it has not been prioritized.

This wasn't reported by anyone from experience, but noticed in code review. Can we downgrade the priority? We haven't prioritized work here and it's been working as needed.

**Comment by arithmetic1728** [comment]
@noahdietz any update on this? It is out of SLO.

**Comment by noahdietz** [comment]
I'd say we should close this. Things have been working and sending an out-of-bounds token is not a necessary test case for GAPICs imo.
