### ISSUE TITLE
Use kokoro for CI/Releasing

### ISSUE THREAD

**Issue by landrito** [googleapis/gapic-showcase#91]
To be consistent with other googleapis repositories.

**Comment by xiaozhenliu-gg5** [comment]
@noahdietz Hi Noah, do you think it brings us benefits to move CI tests to kokoro?

**Comment by noahdietz** [comment]
Not right now. The majority of our tooling repos are on CircleCI. It is easier to manage repos all in the same CI system. We can close this for now since there is no open plan for us to move to Kokoro.
